<!DOCTYPE html>
<html>

<head>
  <title><?= $title ?></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="images/favicon.png">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
  <link href="https://cdn.datatables.net/v/bs4/jq-3.7.0/jszip-3.10.1/dt-2.1.8/af-2.7.0/b-3.2.0/b-colvis-3.2.0/b-html5-3.2.0/b-print-3.2.0/date-1.5.4/fc-5.0.4/fh-4.0.1/kt-2.12.1/r-3.0.3/rg-1.5.1/rr-1.5.0/sc-2.4.3/sb-1.8.1/sl-2.1.0/sr-1.4.1/datatables.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="css/header.css" />


  <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
  <script src="https://cdn.datatables.net/v/bs4/jq-3.7.0/jszip-3.10.1/dt-2.1.8/af-2.7.0/b-3.2.0/b-colvis-3.2.0/b-html5-3.2.0/b-print-3.2.0/date-1.5.4/fc-5.0.4/fh-4.0.1/kt-2.12.1/r-3.0.3/rg-1.5.1/rr-1.5.0/sc-2.4.3/sb-1.8.1/sl-2.1.0/sr-1.4.1/datatables.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>


  <?php if (isset($css_extra)) {
    if (is_array($css_extra)) {
      foreach ($css_extra as $css) {
        echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"$css\" />";
      }
    } else {
      echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"$css_extra\" />";
    }
  } ?>
</head>

<body>
  <!-- Container für die Seite -->
  <div class="container">
    <!-- Überschrift -->
    <h1 class="text-center my-4">Zeiterfassung</h1>

    <!-- Horizontales Menü -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Startseite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="index.php">Benutzer Liste</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="ManageUsers.php">Benutzer verwalten</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="UsersLog.php">Ereignisse Archiv</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="ManageDevices.php">Leser verwalten</a>
          </li>
          <?php
          if (isset($_SESSION['Admin-name'])) { ?>
            <li class="nav-item">
              <a class="nav-link" href="Settings.php"><?= $_SESSION['Admin-name'] ?></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="logout.php">abmelden</a>
            </li>
          <?php } else { ?>
            <li class="nav-item">
              <a class="nav-link" href="login.php">anmelden</a>
            </li>
          <?php } ?>
        </ul>
      </div>
    </nav>
    <!-- Hauptinhalt -->
    <main class="mt-4">
      <?= $html; ?>
    </main>
  </div>
</body>

</html>